import {
  User,
  ProjectOverview,
  AuditLogEntry,
} from "./types";

export const MOCK_USERS: User[] = [
  {
    id: 1,
    username: "karim.elsayed@valentia.com",
    name: "Eng. Karim El-Sayed",
    email: "karim.elsayed@valentia.com",
    role: "ENGINEER",
    phone: "+20 100 555 1234",
    mustChangePassword: false,
    activeProjectsCount: 2,
  },
  {
    id: 2,
    username: "maya.zein@valentia.com",
    name: "Eng. Maya Zein",
    email: "maya.zein@valentia.com",
    role: "ENGINEER",
    phone: "+20 101 222 9876",
    mustChangePassword: false,
    activeProjectsCount: 1,
  },
  {
    id: 3,
    username: "tarek.ramzy@valentia.com",
    name: "Eng. Tarek Ramzy",
    email: "tarek.ramzy@valentia.com",
    role: "ENGINEER",
    phone: "+20 109 444 3322",
    mustChangePassword: true,
    activeProjectsCount: 1,
  },
  {
    id: 4,
    username: "nouran.hassan@valentia.com",
    name: "Nouran Hassan",
    email: "nouran.hassan@valentia.com",
    role: "PROJECT_MANAGER",
    phone: "+20 111 888 4321",
    mustChangePassword: false,
    activeProjectsCount: 6,
  },
  {
    id: 5,
    username: "farid.mansoor@valentia.com",
    name: "Farid Al-Mansoor",
    email: "farid.mansoor@valentia.com",
    role: "COMPANY_OWNER",
    phone: "+20 102 333 7777",
    mustChangePassword: false,
  },
  {
    id: 6,
    username: "admin@valentia.com",
    name: "System Administrator",
    email: "admin@valentia.com",
    role: "ADMINISTRATOR",
    phone: "+20 122 000 9999",
    mustChangePassword: false,
  },
];

export const MOCK_PROJECTS: ProjectOverview[] = [
  {
    id: "proj-105",
    code: "VAL-2026-096",
    title: "Swan Lake Modern Townhouse",
    clientName: "Nadine El-Gammal",
    clientPhone: "+20 102 999 1122",
    clientEmail: "nadine.gammal@example.com",
    customerLocation: {
      country: "Egypt",
      city: "Cairo",
      timezone: "Africa/Cairo",
    },
    representative: {
      representationType: "authorized_representative",
      name: "Sherif El-Gammal",
      relationship: "Brother",
      phone: "+20 100 123 9999",
      email: "sherif.gammal@example.com",
    },
    typology: "TOWNHOUSE",
    areaM2: 340,
    location: "First Settlement, New Cairo",
    compound: "Swan Lake Residences",
    budgetEgp: 8900000,
    status: "SUBMITTED",
    health: "ON_SCHEDULE",
    leadEngineerId: null,
    leadEngineerName: null,
    completionPercent: 10,
    scopeType: "Turnkey Architecture & Full Fit-Out",
    targetTimeline: "Within 6 months",
    notes: "Requires preliminary engineering review and natural light audit for the skylight double-height reception.",
    spaces: [
      { id: "sp-1", name: "Double-Height Reception & Living", type: "LIVING_ROOM", quantity: 1, styleName: "Warm Minimalist" },
      { id: "sp-2", name: "Show & Working Kitchen", type: "KITCHEN", quantity: 1, styleName: "Contemporary Italian" },
      { id: "sp-3", name: "Master Suite & Walk-in Dressing", type: "MASTER_BEDROOM", quantity: 1, styleName: "Japandi Modern" },
      { id: "sp-4", name: "Ensuite Guest Bedrooms", type: "BEDROOM", quantity: 2, styleName: "Warm Minimalist" },
      { id: "sp-5", name: "Private Garden Terrace & Pool Deck", type: "TERRACE", quantity: 1, styleName: "Mediterranean Stone" },
    ],
    nextMilestone: "Intake Review & Lead Architect Assignment",
    nextMilestoneDate: "2026-10-01",
    createdAt: "2026-09-29",
  },
  {
    id: "proj-106",
    code: "VAL-2026-099",
    title: "Marassi Beachside Penthouse",
    clientName: "Omar Abdel-Aziz",
    clientPhone: "+971 52 888 1234",
    clientEmail: "omar.aziz@dubaiinvest.ae",
    customerLocation: {
      country: "United Arab Emirates",
      city: "Dubai",
      timezone: "Asia/Dubai",
    },
    representative: {
      representationType: "valentia_direct",
    },
    typology: "PENTHOUSE",
    areaM2: 260,
    location: "North Coast, Egypt",
    compound: "Marassi - Marina West",
    budgetEgp: 9500000,
    status: "SUBMITTED",
    health: "ON_SCHEDULE",
    leadEngineerId: null,
    leadEngineerName: null,
    completionPercent: 10,
    scopeType: "Luxury Vacation Residence Interior Fit-Out",
    targetTimeline: "Prior to Summer 2027",
    notes: "Client lives in Dubai and chose full direct supervision by Valentia. High moisture & coastal insulation specs required.",
    spaces: [
      { id: "sp-1", name: "Panoramic Sea-View Living", type: "LIVING_ROOM", quantity: 1, styleName: "Mediterranean Luxury" },
      { id: "sp-2", name: "Open Island Kitchen", type: "KITCHEN", quantity: 1, styleName: "Warm Travertine Minimalist" },
      { id: "sp-3", name: "Master Penthouse Suite", type: "MASTER_BEDROOM", quantity: 1, styleName: "Mediterranean Luxury" },
      { id: "sp-4", name: "Rooftop Sunset Lounge & Pergola", type: "BALCONY", quantity: 1, styleName: "Boho Organic Wood" },
    ],
    nextMilestone: "Intake Review & Lead Architect Assignment",
    nextMilestoneDate: "2026-10-02",
    createdAt: "2026-09-28",
  },
  {
    id: "proj-101",
    code: "VAL-2026-081",
    title: "The Horizon Villa",
    clientName: "Tarek Mansour",
    clientPhone: "+971 50 123 4567",
    clientEmail: "tarek.mansour@example.com",
    customerLocation: {
      country: "United Arab Emirates",
      city: "Abu Dhabi",
      timezone: "Asia/Dubai",
    },
    representative: {
      representationType: "client_in_person",
    },
    typology: "VILLA",
    areaM2: 520,
    location: "New Cairo, Egypt",
    compound: "Mivida Parcel 12",
    budgetEgp: 14800000,
    status: "SUBMITTED",
    health: "ON_SCHEDULE",
    leadEngineerId: 1,
    leadEngineerName: "Eng. Karim El-Sayed",
    completionPercent: 20,
    scopeType: "Full Architectural & Turnkey Fit-Out",
    targetTimeline: "Targeting 8 months",
    notes: "Client travels frequently between Abu Dhabi and Cairo. In-person meeting preferred during upcoming visit.",
    spaces: [
      { id: "sp-1", name: "Grand Double-Height Living Lounge", type: "LIVING_ROOM", quantity: 1, styleName: "Warm Minimalist" },
      { id: "sp-2", name: "Formal Dining Suite", type: "DINING", quantity: 1, styleName: "Warm Minimalist" },
      { id: "sp-3", name: "Master Suite & Private Dressing", type: "MASTER_BEDROOM", quantity: 1, styleName: "Neo-Classic Luxury" },
      { id: "sp-4", name: "Show & Preparation Kitchens", type: "KITCHEN", quantity: 2, styleName: "Contemporary Italian" },
      { id: "sp-5", name: "Landscaped Pool Loggia", type: "TERRACE", quantity: 1, styleName: "Mediterranean Stone" },
    ],
    nextMilestone: "Engineering Review & Consultation Preparation",
    nextMilestoneDate: "2026-10-04",
    createdAt: "2026-07-15",
  },
  {
    id: "proj-103",
    code: "VAL-2026-089",
    title: "Uptown Palm Duplex",
    clientName: "Laila Sherif",
    clientPhone: "+20 114 333 2211",
    clientEmail: "laila.sherif@example.com",
    customerLocation: {
      country: "Egypt",
      city: "Cairo",
      timezone: "Africa/Cairo",
    },
    representative: {
      representationType: "client_in_person",
    },
    typology: "DUPLEX",
    areaM2: 290,
    location: "Mokattam, Cairo",
    compound: "Uptown Cairo - Aurora",
    budgetEgp: 7800000,
    status: "SUBMITTED",
    health: "ON_SCHEDULE",
    leadEngineerId: 1,
    leadEngineerName: "Eng. Karim El-Sayed",
    completionPercent: 20,
    scopeType: "Interior Design & Space Planning",
    targetTimeline: "4 months",
    notes: "Client specifications received; preliminary architectural review active.",
    spaces: [
      { id: "sp-1", name: "Open Reception Lounge", type: "LIVING_ROOM", quantity: 1, styleName: "Scandinavian Warmth" },
      { id: "sp-2", name: "Master Bedroom", type: "MASTER_BEDROOM", quantity: 1, styleName: "Scandinavian Warmth" },
      { id: "sp-3", name: "Chef Kitchen", type: "KITCHEN", quantity: 1, styleName: "Modern Minimalist" },
    ],
    nextMilestone: "Engineering Review & Scope Confirmation",
    nextMilestoneDate: "2026-10-02",
    createdAt: "2026-08-20",
  },
  {
    id: "proj-102",
    code: "VAL-2026-084",
    title: "Sky Penthouse Horizon",
    clientName: "Hisham Talaat",
    clientPhone: "+20 100 888 7777",
    clientEmail: "hisham.talaat@example.com",
    customerLocation: {
      country: "Egypt",
      city: "Giza",
      timezone: "Africa/Cairo",
    },
    representative: {
      representationType: "client_in_person",
    },
    typology: "PENTHOUSE",
    areaM2: 410,
    location: "Sheikh Zayed, Giza",
    compound: "Allegria Hills",
    budgetEgp: 11200000,
    status: "SUBMITTED",
    health: "AT_RISK",
    leadEngineerId: 2,
    leadEngineerName: "Eng. Maya Zein",
    completionPercent: 20,
    scopeType: "Turnkey Penthouse Fit-Out",
    targetTimeline: "6 months",
    notes: "Assigned to Eng. Maya Zein. Customer spaces and architectural brief under review.",
    spaces: [
      { id: "sp-1", name: "Sky Living Lounge", type: "LIVING_ROOM", quantity: 1, styleName: "Industrial Elegance" },
      { id: "sp-2", name: "Master Penthouse Suite", type: "MASTER_BEDROOM", quantity: 1, styleName: "Modern Minimalist" },
    ],
    nextMilestone: "Engineering Review & Scope Confirmation",
    nextMilestoneDate: "2026-09-30",
    createdAt: "2026-08-01",
  },
  {
    id: "proj-104",
    code: "VAL-2026-092",
    title: "The Glass Pavilion Villa",
    clientName: "Dr. Khaled Al-Sabah",
    clientPhone: "+965 99 555 444",
    clientEmail: "dr.khaled@kuwaitmed.org",
    customerLocation: {
      country: "Kuwait",
      city: "Kuwait City",
      timezone: "Asia/Kuwait",
    },
    representative: {
      representationType: "authorized_representative",
      name: "Eng. Amr Wahba",
      relationship: "Technical Advisor in Egypt",
      phone: "+20 122 555 4321",
      email: "amr.wahba@advisors.eg",
    },
    typology: "VILLA",
    areaM2: 780,
    location: "New Cairo, Egypt",
    compound: "Lake View Residences",
    budgetEgp: 22400000,
    status: "SUBMITTED",
    health: "ON_SCHEDULE",
    leadEngineerId: 3,
    leadEngineerName: "Eng. Tarek Ramzy",
    completionPercent: 20,
    scopeType: "Comprehensive Luxury Turnkey Commission",
    targetTimeline: "12 months",
    notes: "Comprehensive luxury specifications and drawings under lead architect evaluation.",
    spaces: [
      { id: "sp-1", name: "Grand Entrance Foyer & Lounge", type: "LIVING_ROOM", quantity: 1, styleName: "Neo-Classic Luxury" },
      { id: "sp-2", name: "Formal Banqueting Room", type: "DINING", quantity: 1, styleName: "Neo-Classic Luxury" },
      { id: "sp-3", name: "Royal Master Suite", type: "MASTER_BEDROOM", quantity: 1, styleName: "Neo-Classic Luxury" },
    ],
    nextMilestone: "Engineering Review & Scope Confirmation",
    nextMilestoneDate: "2026-10-05",
    createdAt: "2026-09-02",
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: "2026-09-29 18:40:12",
    actorName: "Nouran Hassan",
    actorRole: "PROJECT_MANAGER",
    action: "ASSIGN_ENGINEER",
    targetEntity: "Project VAL-2026-081",
    details: "Assigned Eng. Karim El-Sayed as Lead Architect for The Horizon Villa",
  },
  {
    id: "log-2",
    timestamp: "2026-09-28 11:20:00",
    actorName: "System Administrator",
    actorRole: "ADMINISTRATOR",
    action: "ELEVATE_USER_ROLE",
    targetEntity: "User #3 (tarek.ramzy@valentia.com)",
    details: "Role updated to ENGINEER and mandatory first login password reset flagged",
  },
  {
    id: "log-3",
    timestamp: "2026-09-27 15:15:33",
    actorName: "System Administrator",
    actorRole: "ADMINISTRATOR",
    action: "CREATE_STAFF_ACCOUNT",
    targetEntity: "User #2 (maya.zein@valentia.com)",
    details: "Created staff account with role ENGINEER for Eng. Maya Zein",
  },
];
