import {
  User,
  ProjectOverview,
  SiteVisit,
  ChangeOrder,
  EngineeringDimensionItem,
  CatalogPackage,
  AuditLogEntry,
} from "./types";

export const MOCK_USERS: User[] = [
  {
    id: 1,
    username: "karim.elsayed@valentia.com",
    name: "Eng. Karim El-Sayed",
    email: "karim.elsayed@valentia.com",
    role: "ENGINEER",
    phone: "+20 100 555 1234",
    mustChangePassword: false,
    activeProjectsCount: 4,
  },
  {
    id: 2,
    username: "maya.zein@valentia.com",
    name: "Eng. Maya Zein",
    email: "maya.zein@valentia.com",
    role: "ENGINEER",
    phone: "+20 101 222 9876",
    mustChangePassword: false,
    activeProjectsCount: 3,
  },
  {
    id: 3,
    username: "tarek.ramzy@valentia.com",
    name: "Eng. Tarek Ramzy",
    email: "tarek.ramzy@valentia.com",
    role: "ENGINEER",
    phone: "+20 109 444 3322",
    mustChangePassword: true,
    activeProjectsCount: 2,
  },
  {
    id: 4,
    username: "nouran.hassan@valentia.com",
    name: "Nouran Hassan",
    email: "nouran.hassan@valentia.com",
    role: "PROJECT_MANAGER",
    phone: "+20 111 888 4321",
    mustChangePassword: false,
    activeProjectsCount: 8,
  },
  {
    id: 5,
    username: "farid.mansoor@valentia.com",
    name: "Farid Al-Mansoor",
    email: "farid.mansoor@valentia.com",
    role: "COMPANY_OWNER",
    phone: "+20 102 333 7777",
    mustChangePassword: false,
  },
  {
    id: 6,
    username: "admin@valentia.com",
    name: "System Administrator",
    email: "admin@valentia.com",
    role: "ADMINISTRATOR",
    phone: "+20 122 000 9999",
    mustChangePassword: false,
  },
];

export const MOCK_PROJECTS: ProjectOverview[] = [
  {
    id: "proj-101",
    code: "VAL-2026-081",
    title: "The Horizon Villa",
    clientName: "Tarek Mansour",
    clientPhone: "+971 50 123 4567",
    typology: "VILLA",
    areaM2: 520,
    location: "New Cairo, Egypt",
    compound: "Mivida Parcel 12",
    budgetEgp: 14800000,
    status: "EXECUTION",
    health: "ON_SCHEDULE",
    leadEngineerId: 1,
    leadEngineerName: "Eng. Karim El-Sayed",
    completionPercent: 68,
    nextMilestone: "Custom Oak Wall Cladding Handover",
    nextMilestoneDate: "2026-10-04",
    createdAt: "2026-07-15",
  },
  {
    id: "proj-102",
    code: "VAL-2026-084",
    title: "Sky Penthouse Horizon",
    clientName: "Hisham Talaat",
    clientPhone: "+20 100 888 7777",
    typology: "PENTHOUSE",
    areaM2: 410,
    location: "Sheikh Zayed, Giza",
    compound: "Allegria Hills",
    budgetEgp: 11200000,
    status: "EXECUTION",
    health: "AT_RISK",
    leadEngineerId: 2,
    leadEngineerName: "Eng. Maya Zein",
    completionPercent: 44,
    nextMilestone: "Acoustic Double-Glazing Installation",
    nextMilestoneDate: "2026-09-30",
    createdAt: "2026-08-01",
  },
  {
    id: "proj-103",
    code: "VAL-2026-089",
    title: "Uptown Palm Duplex",
    clientName: "Laila Sherif",
    clientPhone: "+20 114 333 2211",
    typology: "DUPLEX",
    areaM2: 290,
    location: "Mokattam, Cairo",
    compound: "Uptown Cairo - Aurora",
    budgetEgp: 7800000,
    status: "DESIGN_IN_PROGRESS",
    health: "ON_SCHEDULE",
    leadEngineerId: 1,
    leadEngineerName: "Eng. Karim El-Sayed",
    completionPercent: 32,
    nextMilestone: "3D Axonometric Client Sign-off",
    nextMilestoneDate: "2026-10-02",
    createdAt: "2026-08-20",
  },
  {
    id: "proj-104",
    code: "VAL-2026-092",
    title: "The Glass Pavilion Villa",
    clientName: "Dr. Khaled Al-Sabah",
    clientPhone: "+965 99 555 444",
    typology: "VILLA",
    areaM2: 780,
    location: "New Cairo, Egypt",
    compound: "Lake View Residences",
    budgetEgp: 22400000,
    status: "BOQ_PREPARATION",
    health: "ON_SCHEDULE",
    leadEngineerId: 3,
    leadEngineerName: "Eng. Tarek Ramzy",
    completionPercent: 20,
    nextMilestone: "Itemized Marble & Joinery BOQ Finalization",
    nextMilestoneDate: "2026-09-28",
    createdAt: "2026-09-02",
  },
  {
    id: "proj-105",
    code: "VAL-2026-096",
    title: "Swan Lake Modern Townhouse",
    clientName: "Nadine El-Gammal",
    clientPhone: "+20 102 999 1122",
    typology: "TOWNHOUSE",
    areaM2: 340,
    location: "First Settlement, New Cairo",
    compound: "Swan Lake Residences",
    budgetEgp: 8900000,
    status: "SITE_VISIT_SCHEDULED",
    health: "ON_SCHEDULE",
    leadEngineerId: 2,
    leadEngineerName: "Eng. Maya Zein",
    completionPercent: 8,
    nextMilestone: "Precision Laser Survey & Point Cloud Scan",
    nextMilestoneDate: "2026-09-26",
    createdAt: "2026-09-18",
  },
  {
    id: "proj-106",
    code: "VAL-2026-099",
    title: "Marassi Beachside Penthouse",
    clientName: "Omar Abdel-Aziz",
    clientPhone: "+971 52 888 1234",
    typology: "PENTHOUSE",
    areaM2: 260,
    location: "North Coast, Egypt",
    compound: "Marassi - Marina West",
    budgetEgp: 9500000,
    status: "ENGINEER_REVIEW",
    health: "DELAYED",
    leadEngineerId: 1,
    leadEngineerName: "Eng. Karim El-Sayed",
    completionPercent: 12,
    nextMilestone: "Structural Load & Coastal HVAC Audit",
    nextMilestoneDate: "2026-09-27",
    createdAt: "2026-09-10",
  },
];

export const MOCK_SITE_VISITS: SiteVisit[] = [
  {
    id: "sv-01",
    projectId: "proj-105",
    projectName: "Swan Lake Modern Townhouse",
    clientName: "Nadine El-Gammal",
    clientPhone: "+20 102 999 1122",
    location: "New Cairo, 1st Settlement",
    compound: "Swan Lake - Villa 14-B",
    scheduledDate: "Today",
    scheduledTime: "11:00 AM",
    assignedEngineerId: 1,
    assignedEngineerName: "Eng. Karim El-Sayed",
    status: "IN_PROGRESS",
    laserScanCompleted: true,
    notes: "3D scanner initialized. Verifying ceiling height variation in double-height salon.",
  },
  {
    id: "sv-02",
    projectId: "proj-102",
    projectName: "Sky Penthouse Horizon",
    clientName: "Hisham Talaat",
    clientPhone: "+20 100 888 7777",
    location: "Sheikh Zayed",
    compound: "Allegria Hills - Penthouse 401",
    scheduledDate: "Today",
    scheduledTime: "03:30 PM",
    assignedEngineerId: 1,
    assignedEngineerName: "Eng. Karim El-Sayed",
    status: "ASSIGNED",
    laserScanCompleted: false,
    notes: "Acoustic audit for terrace door seals and chiller sound levels.",
  },
  {
    id: "sv-03",
    projectId: "proj-104",
    projectName: "The Glass Pavilion Villa",
    clientName: "Dr. Khaled Al-Sabah",
    clientPhone: "+965 99 555 444",
    location: "New Cairo",
    compound: "Lake View - Villa 22",
    scheduledDate: "Tomorrow",
    scheduledTime: "10:00 AM",
    assignedEngineerId: 2,
    assignedEngineerName: "Eng. Maya Zein",
    status: "ASSIGNED",
    laserScanCompleted: false,
    notes: "Site visit paid (500 EGP). Client representative Eng. Fadi on site.",
  },
];

export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
  {
    id: "co-201",
    projectId: "proj-101",
    projectName: "The Horizon Villa",
    clientName: "Tarek Mansour",
    title: "Upgrade to Bookmatched Calacatta Viola Marble in Powder Room",
    description: "Client requested replacing standard Navona travertine with bookmatched Italian Calacatta Viola slabs in the ground floor powder room.",
    requestedAt: "2026-09-24",
    costImpactEgp: 185000,
    timeImpactDays: 4,
    status: "PENDING_REVIEW",
  },
  {
    id: "co-202",
    projectId: "proj-102",
    projectName: "Sky Penthouse Horizon",
    clientName: "Hisham Talaat",
    title: "Add Concealed Architectural Lighting in Primary Suite Headboard",
    description: "Integration of 2700K recessed indirect LED profiles with Lutron motorized dimming channel.",
    requestedAt: "2026-09-22",
    costImpactEgp: 48000,
    timeImpactDays: 0,
    status: "APPROVED",
  },
];

export const MOCK_ENGINEERING_ITEMS: EngineeringDimensionItem[] = [
  {
    id: "dim-01",
    spaceName: "Living & Reception",
    parameter: "Gross Floor Area",
    customerEntered: "72.0 m²",
    cadExtracted: "74.8 m²",
    aiInferred: "74.9 m²",
    engineerVerified: "74.82 m²",
    status: "ENGINEER_VERIFIED",
    verifiedBy: "Eng. Karim El-Sayed",
    verifiedAt: "2026-09-24 14:30",
  },
  {
    id: "dim-02",
    spaceName: "Primary Bedroom Suite",
    parameter: "Finished Floor-to-Ceiling Height",
    customerEntered: "3.20 m",
    cadExtracted: "3.45 m (slab to slab)",
    aiInferred: "3.15 m (after MEP drop)",
    engineerVerified: "3.18 m",
    status: "ENGINEER_VERIFIED",
    verifiedBy: "Eng. Karim El-Sayed",
    verifiedAt: "2026-09-24 15:10",
  },
  {
    id: "dim-03",
    spaceName: "Dining Room Glazing",
    parameter: "Acoustic Partition Span",
    customerEntered: "4.80 m width",
    cadExtracted: "4.92 m width",
    aiInferred: "4.90 m width",
    status: "CAD_EXTRACTED",
  },
  {
    id: "dim-04",
    spaceName: "Guest Powder Room",
    parameter: "Plumbing Riser Clearance",
    customerEntered: "Standard 4-inch",
    cadExtracted: "DN110 Riser",
    aiInferred: "Concealed wall cistern compatible",
    status: "AI_INFERRED",
  },
];

export const MOCK_CATALOG_PACKAGES: CatalogPackage[] = [
  {
    id: "pkg-01",
    name: "2D Architectural Drafting & Space Planning",
    type: "2D_BLUEPRINT",
    basePriceEgp: 45000,
    ratePerMeterEgp: 180,
    turnaroundDays: 10,
    includedRevisions: 2,
    isActive: true,
  },
  {
    id: "pkg-02",
    name: "3D Photorealistic CGI & Virtual Reality Walkthrough",
    type: "3D_PHOTOREALISTIC",
    basePriceEgp: 95000,
    ratePerMeterEgp: 320,
    turnaroundDays: 18,
    includedRevisions: 3,
    isActive: true,
  },
  {
    id: "pkg-03",
    name: "Full Turnkey Atelier Fit-Out Execution",
    type: "TURNKEY_FITOUT",
    basePriceEgp: 350000,
    ratePerMeterEgp: 24000,
    turnaroundDays: 90,
    includedRevisions: 5,
    isActive: true,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: "2026-09-25 14:12:05",
    actorName: "Nouran Hassan",
    actorRole: "PROJECT_MANAGER",
    action: "ASSIGN_ENGINEER",
    targetEntity: "Project VAL-2026-081",
    details: "Assigned Eng. Karim El-Sayed as Lead Architect.",
  },
  {
    id: "log-2",
    timestamp: "2026-09-25 12:45:22",
    actorName: "Eng. Karim El-Sayed",
    actorRole: "ENGINEER",
    action: "VERIFY_DIMENSIONS",
    targetEntity: "Project VAL-2026-081 (Living Salon)",
    details: "Laser point cloud certified at 74.82 m² (superseding CAD extraction 74.80 m²).",
  },
  {
    id: "log-3",
    timestamp: "2026-09-25 10:15:30",
    actorName: "Farid Al-Mansoor",
    actorRole: "COMPANY_OWNER",
    action: "APPROVE_CHANGE_ORDER",
    targetEntity: "Project VAL-2026-084",
    details: "Approved CO-202 (Lutron Lighting Upgrade, EGP 48,000).",
  },
  {
    id: "log-4",
    timestamp: "2026-09-24 18:20:11",
    actorName: "System Administrator",
    actorRole: "ADMINISTRATOR",
    action: "UPDATE_CATALOG_RATES",
    targetEntity: "Package PKG-03",
    details: "Adjusted turnkey square meter base from EGP 22,000 to EGP 24,000/m².",
  },
];
