export interface CityOption {
  nameEn: string;
  nameAr: string;
}

export interface CountryOption {
  id: string; // ISO 2-letter code
  nameEn: string;
  nameAr: string;
  flag: string;
  dialCode: string;
  defaultTimezone: string;
  cities: CityOption[];
}

export const COUNTRIES_DATA: CountryOption[] = [
  {
    id: "EG",
    nameEn: "Egypt",
    nameAr: "مصر",
    flag: "🇪🇬",
    dialCode: "+20",
    defaultTimezone: "Africa/Cairo (GMT+2)",
    cities: [
      { nameEn: "Cairo", nameAr: "القاهرة" },
      { nameEn: "New Cairo (Fifth Settlement)", nameAr: "القاهرة الجديدة (التجمع الخامس)" },
      { nameEn: "Sheikh Zayed", nameAr: "الشيخ زايد" },
      { nameEn: "6th of October", nameAr: "السادس من أكتوبر" },
      { nameEn: "North Coast (Sahel)", nameAr: "الساحل الشمالي" },
      { nameEn: "El Gouna", nameAr: "الجونة" },
      { nameEn: "New Administrative Capital", nameAr: "العاصمة الإدارية الجديدة" },
      { nameEn: "Alexandria", nameAr: "الإسكندرية" },
      { nameEn: "Giza", nameAr: "الجيزة" },
      { nameEn: "Maadi", nameAr: "المعادي" },
      { nameEn: "Zamalek", nameAr: "الزمالك" },
      { nameEn: "Heliopolis", nameAr: "مصر الجديدة" },
      { nameEn: "Madinaty & Shorouk", nameAr: "مدينتي والشروق" },
      { nameEn: "Mansoura", nameAr: "المنصورة" },
      { nameEn: "Hurghada", nameAr: "الغردقة" },
      { nameEn: "Sharm El Sheikh", nameAr: "شرم الشيخ" },
      { nameEn: "Tanta", nameAr: "طنطا" },
      { nameEn: "Ismailia", nameAr: "الإسماعيلية" },
      { nameEn: "Port Said", nameAr: "بورسعيد" },
      { nameEn: "Suez", nameAr: "السويس" },
      { nameEn: "Aswan", nameAr: "أسوان" },
      { nameEn: "Luxor", nameAr: "الأقصر" },
      { nameEn: "Assiut", nameAr: "أسيوط" },
      { nameEn: "Sohag", nameAr: "سوهاج" },
      { nameEn: "Damietta", nameAr: "دمياط" },
    ],
  },
  {
    id: "SA",
    nameEn: "Saudi Arabia",
    nameAr: "المملكة العربية السعودية",
    flag: "🇸🇦",
    dialCode: "+966",
    defaultTimezone: "Asia/Riyadh (GMT+3)",
    cities: [
      { nameEn: "Riyadh", nameAr: "الرياض" },
      { nameEn: "Jeddah", nameAr: "جدة" },
      { nameEn: "Dammam", nameAr: "الدمام" },
      { nameEn: "Khobar", nameAr: "الخبر" },
      { nameEn: "Dhahran", nameAr: "الظهران" },
      { nameEn: "Mecca", nameAr: "مكة المكرمة" },
      { nameEn: "Medina", nameAr: "المدينة المنورة" },
      { nameEn: "Tabuk", nameAr: "تبوك" },
      { nameEn: "Abha & Asir", nameAr: "أبها وعسير" },
      { nameEn: "Al Jubail", nameAr: "الجبيل" },
      { nameEn: "Yanbu", nameAr: "ينبع" },
      { nameEn: "Taif", nameAr: "الطائف" },
      { nameEn: "Hail", nameAr: "حائل" },
      { nameEn: "Qassim (Buraidah)", nameAr: "القصيم (بريدة)" },
      { nameEn: "Al-Ula", nameAr: "العلا" },
      { nameEn: "Najran", nameAr: "نجران" },
      { nameEn: "Jazan", nameAr: "جازان" },
    ],
  },
  {
    id: "AE",
    nameEn: "United Arab Emirates",
    nameAr: "الإمارات العربية المتحدة",
    flag: "🇦🇪",
    dialCode: "+971",
    defaultTimezone: "Asia/Dubai (GMT+4)",
    cities: [
      { nameEn: "Dubai", nameAr: "دبي" },
      { nameEn: "Abu Dhabi", nameAr: "أبوظبي" },
      { nameEn: "Sharjah", nameAr: "الشارقة" },
      { nameEn: "Ajman", nameAr: "عجمان" },
      { nameEn: "Ras Al Khaimah", nameAr: "رأس الخيمة" },
      { nameEn: "Fujairah", nameAr: "الفجيرة" },
      { nameEn: "Umm Al Quwain", nameAr: "أم القيوين" },
      { nameEn: "Al Ain", nameAr: "العين" },
    ],
  },
  {
    id: "QA",
    nameEn: "Qatar",
    nameAr: "قطر",
    flag: "🇶🇦",
    dialCode: "+974",
    defaultTimezone: "Asia/Qatar (GMT+3)",
    cities: [
      { nameEn: "Doha", nameAr: "الدوحة" },
      { nameEn: "Lusail", nameAr: "لوسيل" },
      { nameEn: "The Pearl", nameAr: "اللؤلؤة" },
      { nameEn: "Al Rayyan", nameAr: "الريان" },
      { nameEn: "Al Wakrah", nameAr: "الوكرة" },
      { nameEn: "Al Khor", nameAr: "الخور" },
    ],
  },
  {
    id: "KW",
    nameEn: "Kuwait",
    nameAr: "الكويت",
    flag: "🇰🇼",
    dialCode: "+965",
    defaultTimezone: "Asia/Kuwait (GMT+3)",
    cities: [
      { nameEn: "Kuwait City", nameAr: "مدينة الكويت" },
      { nameEn: "Hawalli", nameAr: "حولي" },
      { nameEn: "Salmiya", nameAr: "السالمية" },
      { nameEn: "Al Ahmadi", nameAr: "الأحمدي" },
      { nameEn: "Farwaniya", nameAr: "الفروانية" },
      { nameEn: "Sabah Al Salem", nameAr: "صباح السالم" },
      { nameEn: "Jahra", nameAr: "الجهراء" },
    ],
  },
  {
    id: "BH",
    nameEn: "Bahrain",
    nameAr: "البحرين",
    flag: "🇧🇭",
    dialCode: "+973",
    defaultTimezone: "Asia/Bahrain (GMT+3)",
    cities: [
      { nameEn: "Manama", nameAr: "المنامة" },
      { nameEn: "Riffa", nameAr: "الرفاع" },
      { nameEn: "Muharraq", nameAr: "المحرق" },
      { nameEn: "Hamad Town", nameAr: "مدينة حمد" },
      { nameEn: "Amwaj Islands", nameAr: "جزر أمواج" },
    ],
  },
  {
    id: "OM",
    nameEn: "Oman",
    nameAr: "سلطنة عمان",
    flag: "🇴🇲",
    dialCode: "+968",
    defaultTimezone: "Asia/Muscat (GMT+4)",
    cities: [
      { nameEn: "Muscat", nameAr: "مسقط" },
      { nameEn: "Salalah", nameAr: "صلالة" },
      { nameEn: "Sohar", nameAr: "صحار" },
      { nameEn: "Nizwa", nameAr: "نزوى" },
      { nameEn: "Sur", nameAr: "صور" },
    ],
  },
  {
    id: "JO",
    nameEn: "Jordan",
    nameAr: "الأردن",
    flag: "🇯🇴",
    dialCode: "+962",
    defaultTimezone: "Asia/Amman (GMT+3)",
    cities: [
      { nameEn: "Amman", nameAr: "عمان" },
      { nameEn: "Irbid", nameAr: "إربد" },
      { nameEn: "Zarqa", nameAr: "الزرقاء" },
      { nameEn: "Aqaba", nameAr: "العقبة" },
      { nameEn: "Dead Sea", nameAr: "البحر الميت" },
    ],
  },
  {
    id: "LB",
    nameEn: "Lebanon",
    nameAr: "لبنان",
    flag: "🇱🇧",
    dialCode: "+961",
    defaultTimezone: "Asia/Beirut (GMT+2)",
    cities: [
      { nameEn: "Beirut", nameAr: "بيروت" },
      { nameEn: "Tripoli", nameAr: "طرابلس" },
      { nameEn: "Sidon", nameAr: "صيدا" },
      { nameEn: "Jounieh", nameAr: "جونيه" },
      { nameEn: "Byblos", nameAr: "جبيل" },
    ],
  },
  {
    id: "IQ",
    nameEn: "Iraq",
    nameAr: "العراق",
    flag: "🇮🇶",
    dialCode: "+964",
    defaultTimezone: "Asia/Baghdad (GMT+3)",
    cities: [
      { nameEn: "Baghdad", nameAr: "بغداد" },
      { nameEn: "Erbil", nameAr: "أربيل" },
      { nameEn: "Basra", nameAr: "البصرة" },
      { nameEn: "Sulaymaniyah", nameAr: "السليمانية" },
      { nameEn: "Najaf", nameAr: "النجف" },
    ],
  },
  {
    id: "GB",
    nameEn: "United Kingdom",
    nameAr: "المملكة المتحدة",
    flag: "🇬🇧",
    dialCode: "+44",
    defaultTimezone: "Europe/London (GMT+0)",
    cities: [
      { nameEn: "London", nameAr: "لندن" },
      { nameEn: "Manchester", nameAr: "مانشستر" },
      { nameEn: "Birmingham", nameAr: "برمنغهام" },
      { nameEn: "Edinburgh", nameAr: "إدنبرة" },
      { nameEn: "Glasgow", nameAr: "غلاسكو" },
      { nameEn: "Leeds", nameAr: "ليدز" },
      { nameEn: "Liverpool", nameAr: "ليفربول" },
      { nameEn: "Bristol", nameAr: "بريستول" },
      { nameEn: "Oxford", nameAr: "أكسفورد" },
      { nameEn: "Cambridge", nameAr: "كامبريدج" },
    ],
  },
  {
    id: "US",
    nameEn: "United States",
    nameAr: "الولايات المتحدة",
    flag: "🇺🇸",
    dialCode: "+1",
    defaultTimezone: "America/New_York (GMT-5)",
    cities: [
      { nameEn: "New York", nameAr: "نيويورك" },
      { nameEn: "Los Angeles", nameAr: "لوس أنجلوس" },
      { nameEn: "Miami", nameAr: "ميامي" },
      { nameEn: "Chicago", nameAr: "شيكاغو" },
      { nameEn: "Houston", nameAr: "هيوستن" },
      { nameEn: "San Francisco", nameAr: "سان فرانسيسكو" },
      { nameEn: "Washington D.C.", nameAr: "واشنطن" },
      { nameEn: "Dallas", nameAr: "دالاس" },
      { nameEn: "Boston", nameAr: "بوسطن" },
      { nameEn: "Seattle", nameAr: "سياتل" },
      { nameEn: "Atlanta", nameAr: "أتلانتا" },
    ],
  },
  {
    id: "CA",
    nameEn: "Canada",
    nameAr: "كندا",
    flag: "🇨🇦",
    dialCode: "+1",
    defaultTimezone: "America/Toronto (GMT-5)",
    cities: [
      { nameEn: "Toronto", nameAr: "تورونتو" },
      { nameEn: "Montreal", nameAr: "مونتريال" },
      { nameEn: "Vancouver", nameAr: "فانكوفر" },
      { nameEn: "Calgary", nameAr: "كالجاري" },
      { nameEn: "Ottawa", nameAr: "أوتاوا" },
    ],
  },
  {
    id: "FR",
    nameEn: "France",
    nameAr: "فرنسا",
    flag: "🇫🇷",
    dialCode: "+33",
    defaultTimezone: "Europe/Paris (GMT+1)",
    cities: [
      { nameEn: "Paris", nameAr: "باريس" },
      { nameEn: "Nice", nameAr: "نيس" },
      { nameEn: "Cannes", nameAr: "كان" },
      { nameEn: "Lyon", nameAr: "ليون" },
      { nameEn: "Marseille", nameAr: "مرسيليا" },
      { nameEn: "Bordeaux", nameAr: "بوردو" },
    ],
  },
  {
    id: "DE",
    nameEn: "Germany",
    nameAr: "ألمانيا",
    flag: "🇩🇪",
    dialCode: "+49",
    defaultTimezone: "Europe/Berlin (GMT+1)",
    cities: [
      { nameEn: "Berlin", nameAr: "برلين" },
      { nameEn: "Munich", nameAr: "ميونيخ" },
      { nameEn: "Frankfurt", nameAr: "فرانكفورت" },
      { nameEn: "Hamburg", nameAr: "هامبورغ" },
      { nameEn: "Dusseldorf", nameAr: "دوسلدورف" },
      { nameEn: "Stuttgart", nameAr: "شتوتغارت" },
    ],
  },
  {
    id: "IT",
    nameEn: "Italy",
    nameAr: "إيطاليا",
    flag: "🇮🇹",
    dialCode: "+39",
    defaultTimezone: "Europe/Rome (GMT+1)",
    cities: [
      { nameEn: "Milan", nameAr: "ميلانو" },
      { nameEn: "Rome", nameAr: "روما" },
      { nameEn: "Florence", nameAr: "فلورنسا" },
      { nameEn: "Venice", nameAr: "البندقية" },
      { nameEn: "Turin", nameAr: "تورينو" },
      { nameEn: "Como", nameAr: "كومو" },
    ],
  },
  {
    id: "CH",
    nameEn: "Switzerland",
    nameAr: "سويسرا",
    flag: "🇨🇭",
    dialCode: "+41",
    defaultTimezone: "Europe/Zurich (GMT+1)",
    cities: [
      { nameEn: "Geneva", nameAr: "جنيف" },
      { nameEn: "Zurich", nameAr: "زيورخ" },
      { nameEn: "Lausanne", nameAr: "لوزان" },
      { nameEn: "Basel", nameAr: "بازل" },
      { nameEn: "Lugano", nameAr: "لوغانو" },
    ],
  },
  {
    id: "ES",
    nameEn: "Spain",
    nameAr: "إسبانيا",
    flag: "🇪🇸",
    dialCode: "+34",
    defaultTimezone: "Europe/Madrid (GMT+1)",
    cities: [
      { nameEn: "Madrid", nameAr: "مدريد" },
      { nameEn: "Barcelona", nameAr: "برشلونة" },
      { nameEn: "Marbella", nameAr: "ماربيا" },
      { nameEn: "Valencia", nameAr: "فالنسيا" },
      { nameEn: "Malaga", nameAr: "مالقة" },
    ],
  },
  {
    id: "NL",
    nameEn: "Netherlands",
    nameAr: "هولندا",
    flag: "🇳🇱",
    dialCode: "+31",
    defaultTimezone: "Europe/Amsterdam (GMT+1)",
    cities: [
      { nameEn: "Amsterdam", nameAr: "أمستردام" },
      { nameEn: "Rotterdam", nameAr: "روتردام" },
      { nameEn: "The Hague", nameAr: "لاهاي" },
      { nameEn: "Utrecht", nameAr: "أوترخت" },
    ],
  },
  {
    id: "BE",
    nameEn: "Belgium",
    nameAr: "بلجيكا",
    flag: "🇧🇪",
    dialCode: "+32",
    defaultTimezone: "Europe/Brussels (GMT+1)",
    cities: [
      { nameEn: "Brussels", nameAr: "بروكسل" },
      { nameEn: "Antwerp", nameAr: "أنتويرب" },
      { nameEn: "Ghent", nameAr: "غنت" },
    ],
  },
  {
    id: "AT",
    nameEn: "Austria",
    nameAr: "النمسا",
    flag: "🇦🇹",
    dialCode: "+43",
    defaultTimezone: "Europe/Vienna (GMT+1)",
    cities: [
      { nameEn: "Vienna", nameAr: "فيينا" },
      { nameEn: "Salzburg", nameAr: "سالزبورغ" },
      { nameEn: "Innsbruck", nameAr: "إنسبروك" },
    ],
  },
  {
    id: "TR",
    nameEn: "Turkey",
    nameAr: "تركيا",
    flag: "🇹🇷",
    dialCode: "+90",
    defaultTimezone: "Europe/Istanbul (GMT+3)",
    cities: [
      { nameEn: "Istanbul", nameAr: "إسطنبول" },
      { nameEn: "Ankara", nameAr: "أنقرة" },
      { nameEn: "Antalya", nameAr: "أنطاليا" },
      { nameEn: "Bodrum", nameAr: "بودروم" },
      { nameEn: "Izmir", nameAr: "إزمير" },
    ],
  },
  {
    id: "MA",
    nameEn: "Morocco",
    nameAr: "المغرب",
    flag: "🇲🇦",
    dialCode: "+212",
    defaultTimezone: "Africa/Casablanca (GMT+1)",
    cities: [
      { nameEn: "Casablanca", nameAr: "الدار البيضاء" },
      { nameEn: "Rabat", nameAr: "الرباط" },
      { nameEn: "Marrakech", nameAr: "مراكش" },
      { nameEn: "Tangier", nameAr: "طنجة" },
      { nameEn: "Fez", nameAr: "فاس" },
    ],
  },
  {
    id: "AU",
    nameEn: "Australia",
    nameAr: "أستراليا",
    flag: "🇦🇺",
    dialCode: "+61",
    defaultTimezone: "Australia/Sydney (GMT+10)",
    cities: [
      { nameEn: "Sydney", nameAr: "سيدني" },
      { nameEn: "Melbourne", nameAr: "ملبورن" },
      { nameEn: "Brisbane", nameAr: "بريزبان" },
      { nameEn: "Perth", nameAr: "بيرث" },
    ],
  },
  {
    id: "GR",
    nameEn: "Greece",
    nameAr: "اليونان",
    flag: "🇬🇷",
    dialCode: "+30",
    defaultTimezone: "Europe/Athens (GMT+2)",
    cities: [
      { nameEn: "Athens", nameAr: "أثينا" },
      { nameEn: "Thessaloniki", nameAr: "سالونيك" },
      { nameEn: "Mykonos", nameAr: "ميكونوس" },
      { nameEn: "Santorini", nameAr: "سانتوريني" },
    ],
  },
  {
    id: "CY",
    nameEn: "Cyprus",
    nameAr: "قبرص",
    flag: "🇨🇾",
    dialCode: "+357",
    defaultTimezone: "Asia/Nicosia (GMT+2)",
    cities: [
      { nameEn: "Limassol", nameAr: "ليماسول" },
      { nameEn: "Nicosia", nameAr: "نيقوسيا" },
      { nameEn: "Paphos", nameAr: "بافوس" },
      { nameEn: "Larnaca", nameAr: "لارنكا" },
    ],
  },
  {
    id: "SE",
    nameEn: "Sweden",
    nameAr: "السويد",
    flag: "🇸🇪",
    dialCode: "+46",
    defaultTimezone: "Europe/Stockholm (GMT+1)",
    cities: [
      { nameEn: "Stockholm", nameAr: "ستوكهولم" },
      { nameEn: "Gothenburg", nameAr: "غوتنبرغ" },
      { nameEn: "Malmo", nameAr: "مالمو" },
    ],
  },
  {
    id: "NO",
    nameEn: "Norway",
    nameAr: "النرويج",
    flag: "🇳🇴",
    dialCode: "+47",
    defaultTimezone: "Europe/Oslo (GMT+1)",
    cities: [
      { nameEn: "Oslo", nameAr: "أوسلو" },
      { nameEn: "Bergen", nameAr: "بيرغن" },
    ],
  },
  {
    id: "DK",
    nameEn: "Denmark",
    nameAr: "الدنمارك",
    flag: "🇩🇰",
    dialCode: "+45",
    defaultTimezone: "Europe/Copenhagen (GMT+1)",
    cities: [
      { nameEn: "Copenhagen", nameAr: "كوبنهاغن" },
      { nameEn: "Aarhus", nameAr: "آرهوس" },
    ],
  },
  {
    id: "SG",
    nameEn: "Singapore",
    nameAr: "سنغافورة",
    flag: "🇸🇬",
    dialCode: "+65",
    defaultTimezone: "Asia/Singapore (GMT+8)",
    cities: [
      { nameEn: "Singapore", nameAr: "سنغافورة" },
    ],
  },
  {
    id: "JP",
    nameEn: "Japan",
    nameAr: "اليابان",
    flag: "🇯🇵",
    dialCode: "+81",
    defaultTimezone: "Asia/Tokyo (GMT+9)",
    cities: [
      { nameEn: "Tokyo", nameAr: "طوكيو" },
      { nameEn: "Kyoto", nameAr: "كيوتو" },
      { nameEn: "Osaka", nameAr: "أوساكا" },
    ],
  },
];

/**
 * Helper to find country by name (either EN or AR) or code
 */
export function findCountry(query: string): CountryOption | undefined {
  if (!query) return undefined;
  const q = query.trim().toLowerCase();
  return COUNTRIES_DATA.find(
    (c) =>
      c.id.toLowerCase() === q ||
      c.nameEn.toLowerCase() === q ||
      c.nameAr.toLowerCase() === q ||
      c.nameEn.toLowerCase().includes(q) ||
      c.nameAr.includes(q)
  );
}

/**
 * Helper to get country by dial code
 */
export function findCountryByDialCode(dialCode: string): CountryOption | undefined {
  if (!dialCode) return undefined;
  const cleanCode = dialCode.trim();
  return COUNTRIES_DATA.find((c) => c.dialCode === cleanCode);
}
